# Generated by Django 4.2 on 2025-06-25 23:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
